// Copyright (c) Knowledge & Experience. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
using Kae.Tools.Generator.Coloring;
using System;
using System.Collections.Generic;

namespace Kae.Tools.Generator
{
    public interface IGenerator
    {
        public string Version { get; set; }
        public string DomainName { get; }

        public IList<Context.ContextParam> ContextParams { get; }

        public ColoringRepository Coloring { get; set; }

        public ColoringManager ColoringManager { get; }

        public utility.GenFolder GenFolder { get; }

        public void ResolveContext();
        public void LoadMetaModel();
        public void LoadDomainModels();

        /// <summary>
        /// deprecated method
        /// </summary>
        public void Generate();

        /// <summary>
        /// Generate environment for contents that will be generated by GenerateContent() methods.
        /// For example, project folder and project file for the case of C#.
        /// </summary>
        public bool GenerateEnvironment();


        public void GenerateContents();
    }
}
